#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
修复DMVPN服务器配置 - 切换到anonymous模式
解决: ERROR: exchange Identity Protection not allowed in any applicable rmconf
"""

import paramiko
import datetime

# 服务器信息
SERVER_IP = "192.168.50.48"
SERVER_PORT = 22
SERVER_USER = "yuxy"
SERVER_PASS = "milesight123"

# 新的Racoon配置（anonymous模式）
NEW_RACOON_CONFIG = """# Racoon configuration for DMVPN Server
# Generated by DMVPN Server Config Tool v2.2
# Date: {}
# Mode: Anonymous (Allow any router IP)

path pre_shared_key "/etc/racoon/psk.txt";
path certificate "/etc/racoon/certs";

log info;

# Accept connections from any router (anonymous mode)
remote anonymous {{
    exchange_mode main;
    my_identifier address;
    peers_identifier address;

    nat_traversal on;

    proposal {{
        encryption_algorithm aes 128;
        hash_algorithm sha1;
        authentication_method pre_shared_key;
        dh_group modp4096;
        lifetime time 10800 sec;
    }}

    dpd_delay 30;
    dpd_retry 5;
    dpd_maxfail 5;
}}

sainfo anonymous {{
    # pfs_group disabled
    lifetime time 3600 sec;

    encryption_algorithm aes 128;
    authentication_algorithm hmac_sha1;
    compression_algorithm deflate;
}}
""".format(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))


def run_ssh_command(ssh_client, command, use_sudo=True):
    """执行SSH命令"""
    if use_sudo and not command.startswith("sudo"):
        command = f"echo '{SERVER_PASS}' | sudo -S {command}"

    stdin, stdout, stderr = ssh_client.exec_command(command)
    out = stdout.read().decode('utf-8', errors='ignore')
    err = stderr.read().decode('utf-8', errors='ignore')
    return out, err


def main():
    print("=" * 60)
    print("修复DMVPN服务器配置")
    print("=" * 60)

    # 连接SSH
    print(f"\n1. 连接到服务器 {SERVER_IP}...")
    ssh_client = paramiko.SSHClient()
    ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    try:
        ssh_client.connect(
            hostname=SERVER_IP,
            port=SERVER_PORT,
            username=SERVER_USER,
            password=SERVER_PASS,
            timeout=10
        )
        print("   [OK] SSH连接成功")

        # 备份当前配置
        print("\n2. 备份当前配置...")
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_file = f"/etc/racoon/racoon.conf.bak.{timestamp}"
        run_ssh_command(ssh_client, f"cp /etc/racoon/racoon.conf {backup_file}")
        print(f"   [OK] 备份完成: {backup_file}")

        # 写入新配置到临时文件
        print("\n3. 写入新配置...")
        config_escaped = NEW_RACOON_CONFIG.replace("'", "'\\''")
        run_ssh_command(ssh_client, f"echo '{config_escaped}' > /tmp/racoon.conf", use_sudo=False)

        # 复制到正式位置
        run_ssh_command(ssh_client, "cp /tmp/racoon.conf /etc/racoon/racoon.conf")
        run_ssh_command(ssh_client, "chmod 644 /etc/racoon/racoon.conf")
        print("   [OK] 配置文件已更新")

        # 验证配置语法
        print("\n4. 验证配置语法...")
        out, err = run_ssh_command(ssh_client, "racoon -C -f /etc/racoon/racoon.conf")
        if err and "ERROR" in err:
            print(f"   [ERROR] 配置语法错误:\n{err}")
            return False
        else:
            print("   [OK] 配置语法正确")

        # 重启DMVPN服务（使用dmvpn.sh脚本）
        print("\n5. 重启DMVPN服务...")

        # Stop DMVPN
        run_ssh_command(ssh_client, "cd /home && sh dmvpn.sh stop")

        import time
        time.sleep(2)

        # Start DMVPN
        run_ssh_command(ssh_client, "cd /home && sh dmvpn.sh start")

        time.sleep(3)

        # 检查服务状态
        print("\n6. 检查服务状态...")
        out, err = run_ssh_command(ssh_client, "systemctl status racoon", use_sudo=False)

        if "active (running)" in out:
            print("   [OK] Racoon服务运行正常")
            print("\n" + "=" * 60)
            print("配置修复完成！")
            print("=" * 60)
            print("\n已切换到anonymous模式，现在可以接受任意IP的路由器连接。")
            print("\n请在路由器端检查DMVPN连接状态。")
            return True
        else:
            print("   [ERROR] Racoon服务状态异常")
            print("\n服务状态:")
            for line in out.split('\n')[:15]:
                if line.strip():
                    print(f"  {line}")

            # 查看日志
            print("\n最近的错误日志:")
            out, _ = run_ssh_command(ssh_client, "journalctl -u racoon -n 20 --no-pager", use_sudo=False)
            for line in out.split('\n')[-10:]:
                if line.strip():
                    print(f"  {line}")
            return False

    except Exception as e:
        print(f"\n[ERROR] 错误: {str(e)}")
        return False

    finally:
        ssh_client.close()


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
